### ISSUE TITLE
Python snippets for 9.7inch e-Paper

### ISSUE THREAD

**Issue by sabuhish** [soonuse/epd-library-python#10]
Thank you so much for your help, appreciated it a lot. can you share some tips or code examples for 9.7 inch as well?It will definitely would be great if you could do that. thanks in advance!

**Comment by kudchikarsk** [comment]
> Thank you so much for your help, appreciated it a lot. can you share some tips or code examples for 9.7 inches as well? It will definitely would be great if you could do that. thanks in advance!

Hi, Sabuhish 
even I'm trying to accomplish the same thing did you find a solution to the problem?

**Comment by gerald-lbn** [comment]
Hi, Sabuhish
If could add support for the 9.7 inche epd that would be great!

**Comment by soonuse** [comment]
Thanks to danielneumann and GregDMeyer, 9.7 inches is supported now.
