### ISSUE TITLE
How to print second color and not just monocolor.bmp?

### ISSUE THREAD

**Issue by Norfeldt** [soonuse/epd-library-python#15]
Thank you so much for this great repo!  I got it working* and it printed! YES

Now the question I have is how do I print with the second color (got a 7.5 white, black and red display)?

*followed the instructions but had to do`pip --no-cache-dir install spidev` and use another font because I didn't had `FreeMonoBold.ttf`

**Comment by soonuse** [comment]
See the code of 7.5inch_e-paper_b/raspberrypi/python/epd7in5b.py: these 2 methods get_frame_buffer(self, image) and display_frame(self, frame_buffer).
get_frame_buffer() converts the PIL image to a gray scale image buffer. If the gray scale of a pixel less than 64, it will be colored as black. Besides, gray scale between [64, 192) to red; [192, 255) to white.

Then, what the display_frame() done was convert the pixel to the format taking 3 bits to match 1 pixel.
You can see the chapter of Data Start Transmission on the datasheet.
