### ISSUE TITLE
Support for 7.8 inch Driver and Code Samples for python

### ISSUE THREAD

**Issue by QA71** [soonuse/epd-library-python#16]
Hello
I'm new to programming and i want to connect 7.8 ws with rPİ. And I know a little python. So can anyone explain me step by step how to setup this.
Final program will write some data on ePaper as quick as possible using Python code. Also i want to use Partial refresh.
Thank you

**Comment by soonuse** [comment]
See https://www.waveshare.com/wiki/7.8inch_e-Paper_HAT for more details and try this https://github.com/waveshare/IT8951-ePaper.git

This one isn't written in Python, but I hope it will help you.

The description of git is written in Chinese, however, you can follow the command lines:

```
git clone https://github.com/waveshare/IT8951-ePaper.git
cd IT8951-ePaper
make
```
then
```
sudo ./epd -2.51
```
the param -2.51 is used to set the VCOM voltage.

You can get the latest updates on Waveshare's github. I thank you for your support however, I no longer maintain e-paper projects.
