### ISSUE TITLE
unable to write horizontal text

### ISSUE THREAD

**Issue by YaddyVirus** [soonuse/epd-library-python#2]
is there anyway to write text horizontally?

**Comment by soonuse** [comment]
The demos are based on PIL library, which allows you to rotate the canvas, e.g.
    image = Image.new('1', (EPD_HEIGHT, EPD_WIDTH), 1)
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype('/usr/share/fonts/truetype/freefont/FreeMonoBold.ttf', 24)
    draw.text((100, 10), 'e-Paper demo', font = font, fill = 255)
    newimg = image.rotate(90)
... ...
There may be a better idea.

**Comment by YaddyVirus** [comment]
@soonuse I took a different approach. I made a BMP image with the strings, rotated and resized it and displayed that BMP on the screen
